Input component
lsoldano93/2DPlatformer pull request #2
Opened 2022-09-29 02:24 UTC by csimpson1

DON'T MERGE, WILL CAUSE BUILD TO FAIL

When compiling I get the following error:

MSBuild version 17.3.1+2badb37d1 for .NET Framework
  StdKeyBoardCtrlScheme.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\xmemory(678,18): error C2672: 'std::construct_at': no matching overloaded function found [D:\workspace\2DPlatformer2\build\2DPlatformer.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\xutility(223,16): message : could be '_Ty *std::construct_at(_Ty *const ,_Types &&...) noexcept(<expr>)' [D:\workspace\2DPlatformer2\build\2DPlatformer.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\xmemory(1661): message : see reference to function template instantiation 'void std::_Default_allocator_traits<_Alloc>::construct<_Ty,Command&>(_Alloc &,_Objty *const ,Command &)' being compiled [D:\workspace\2DPlatformer2\build\2DPlatfo
rmer.vcxproj]
          with
          [
              _Alloc=std::allocator<Command>,
              _Ty=Command,
              _Objty=Command
          ]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\xmemory(1662): message : see reference to function template instantiation 'void std::_Default_allocator_traits<_Alloc>::construct<_Ty,Command&>(_Alloc &,_Objty *const ,Command &)' being compiled [D:\workspace\2DPlatformer2\build\2DPlatfo
rmer.vcxproj]
          with
          [
              _Alloc=std::allocator<Command>,
              _Ty=Command,
              _Objty=Command
          ]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\xmemory(1679): message : see reference to function template instantiation 'void std::_Uninitialized_backout_al<std::allocator<Command>>::_Emplace_back<Command&>(Command &)' being compiled [D:\workspace\2DPlatformer2\build\2DPlatformer.vc
xproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\xmemory(1701): message : see reference to function template instantiation 'void std::_Uninitialized_backout_al<std::allocator<Command>>::_Emplace_back<Command&>(Command &)' being compiled [D:\workspace\2DPlatformer2\build\2DPlatformer.vc
xproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\vector(1918): message : see reference to function template instantiation 'Command *std::_Uninitialized_copy<Command*,std::allocator<Command>>(const _InIt,const _InIt,Command *,_Alloc &)' being compiled [D:\workspace\2DPlatformer2\build\2
DPlatformer.vcxproj]
          with
          [
              _InIt=Command *,
              _Alloc=std::allocator<Command>
          ]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\vector(726): message : see reference to function template instantiation 'void std::vector<Command,std::allocator<Command>>::_Construct_n<Command*const &,Command*const &>(const unsigned __int64,Command *const &,Command *const &)' being co
mpiled [D:\workspace\2DPlatformer2\build\2DPlatformer.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\vector(726): message : see reference to function template instantiation 'void std::vector<Command,std::allocator<Command>>::_Construct_n<Command*const &,Command*const &>(const unsigned __int64,Command *const &,Command *const &)' being co
mpiled [D:\workspace\2DPlatformer2\build\2DPlatformer.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\vector(722): message : while compiling class template member function 'std::vector<Command,std::allocator<Command>>::vector(const std::vector<Command,std::allocator<Command>> &)' [D:\workspace\2DPlatformer2\build\2DPlatformer.vcxproj]
D:\workspace\2DPlatformer2\src\ControlScheme\StdKeyBoardCtrlScheme.cpp(40): message : see reference to function template instantiation 'std::vector<Command,std::allocator<Command>>::vector(const std::vector<Command,std::allocator<Command>> &)' being compiled [D:\workspace\2DPlatformer2\build\2DPlatformer.vcxproj]
D:\workspace\2DPlatformer2\src\ControlScheme\StdKeyBoardCtrlScheme.cpp(24): message : see reference to class template instantiation 'std::vector<Command,std::allocator<Command>>' being compiled [D:\workspace\2DPlatformer2\build\2DPlatformer.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\xmemory(675): error C2259: 'Command': cannot instantiate abstract class [D:\workspace\2DPlatformer2\build\2DPlatformer.vcxproj]
D:\workspace\2DPlatformer2\src\Command\Command.hpp(3): message : see declaration of 'Command' [D:\workspace\2DPlatformer2\build\2DPlatformer.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\xmemory(675): message : due to following members: [D:\workspace\2DPlatformer2\build\2DPlatformer.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\xmemory(675): message : 'void Command::execute(void)': is abstract [D:\workspace\2DPlatformer2\build\2DPlatformer.vcxproj]
D:\workspace\2DPlatformer2\src\Command\Command.hpp(6): message : see declaration of 'Command::execute' [D:\workspace\2DPlatformer2\build\2DPlatformer.vcxproj]
  SDL2.vcxproj -> D:\workspace\2DPlatformer2\build\_deps\sdl2-build\Debug\SDL2d.dll
  SDL2-static.vcxproj -> D:\workspace\2DPlatformer2\build\_deps\sdl2-build\Debug\SDL2-staticd.lib
  SDL2_test.vcxproj -> D:\workspace\2DPlatformer2\build\_deps\sdl2-build\Debug\SDL2_test.lib
  SDL2main.vcxproj -> D:\workspace\2DPlatformer2\build\_deps\sdl2-build\Debug\SDL2maind.lib

2022-10-04 01:33 UTC, lsoldano93 commented on src/CMakeLists.txt
> +add_subdirectory(${CMAKE_CURRENT_LIST_DIR}/ControlScheme)
We'll prob have to match up on directory capitalization later, but its good for now

2022-10-04 01:58 UTC, lsoldano93 requested changes
Looks good dude, just some small stuff! Super impressed with your skills as someone who is new to C++!

2022-10-04 01:58 UTC, lsoldano93 commented on src/Command/Command.hpp
> +      ~Command() = default;
Make sure we label our destructors virtual unless there's a reason for us specifically not to, which idt I have personally encountered before

2022-10-04 01:58 UTC, lsoldano93 commented on src/Command/Command.hpp
> +      ~Command() = default;
Also for what it's worth you don't need to use the rule of 5 here, it doesn't hurt to default everything it's just unnecessary and costing you a few more key strokes than you probably want

2022-10-04 01:58 UTC, lsoldano93 commented on src/ControlScheme/CMakeLists.txt
> +set(CONTROL_SCHEME_FILES
Make sure to call this CONTROL_SCHEME_SOURCE_FILES as that's what makes it obvious that we are dealing with .cpp's and .c's, whereas if you do CONTROL_SCHEME_FILES it's a little generalized... Of course once you do that you will have to update the upper level CMakes to accomodate as well.

2022-10-04 01:58 UTC, lsoldano93 commented on src/ControlScheme/CMakeLists.txt
>      #${CMAKE_CURRENT_LIST_DIR}/
Delete this line

2022-10-04 01:58 UTC, lsoldano93 commented on src/ControlScheme/CMakeLists.txt
>      #${CMAKE_CURRENT_LIST_DIR}/
Delete this line

2022-10-04 01:58 UTC, lsoldano93 commented on src/ControlScheme/ControlScheme.hpp
> +      virtual ~ControlScheme() {}
Prefer = default() instead of {}

2022-10-04 01:58 UTC, lsoldano93 commented on src/ControlScheme/ControlScheme.hpp
> +      virtual std::shared_ptr<Command> translate(SDL_Event * e) = 0;
I guess it would be cool to have a little more detailed function name to explain what the translation is

2022-10-04 01:58 UTC, lsoldano93 commented on src/ControlScheme/ControlScheme.hpp
> +   /*
Is this comment for the above map?

2022-10-04 01:58 UTC, lsoldano93 commented on src/ControlScheme/ControlScheme.hpp
> +      std::map<SDL_Keycode, std::vector<std::shared_ptr<Command>>> m_scheme;
Can we give a more detailed name for this map like, m_keycode_to_command_map or something?

2022-10-04 01:58 UTC, lsoldano93 commented on src/ControlScheme/StdKeyBoardCtrlScheme.cpp
> +	this->m_scheme.emplace(SDLK_a, handleMoveLeft);
It would be more efficient for these emplacements to just put everything you have in the curly braces above directly into the second position of emplace so you dont create a vector, and then copy it into a new vector. Alternatively you can create the vector as you are now and call std::move(handleMoveLeft) within your emplace call to move the existing vector (and kill it) into the map

2022-10-04 01:58 UTC, lsoldano93 commented on src/ControlScheme/StdKeyBoardCtrlScheme.cpp
> +	using std::vector;
So right here is a big "look out!" We should never take a pointer as input WITHOUT verifying it is non null. If we call evt and it was passed in as null we will crash the program... In order to use some of the tools I've added look at the ProjectDef files and use the macro called CHECK_FOR_NULL_PTR. You can call that first and if the pointer is null it will automatically log for you and back out... You may need to add a macro in this case that returns a nullptr if a nullptr is detected.

2022-10-04 01:58 UTC, lsoldano93 commented on src/ControlScheme/StdKeyBoardCtrlScheme.cpp
> +			throw std::out_of_range("Command misspecified!");
So I'm just going to suggest we don't ever really throw exceptions. I think people go either way in that some people always throw and others never do, I'm more in the latter camp. I don't throw unless it's something absolutely critical that will prevent run at the setup stages. Otherwise here we can just return null and use an assert + log to throw IN CASE we are in debug mode and this is what's expected.

Further it doesn't really make sense to throw and catch within the same scope, in that case you may as well just return otherwise you're adding unnecessary logic.

2022-10-04 01:58 UTC, lsoldano93 commented on src/ControlScheme/StdKeyBoardCtrlScheme.cpp
> -				else if(translatedEvent.length > 1 && *evt.type == SDL_KEYUP) {
Instead of dereferencing pointers to access (AKA *evt.type) just use the pointer designation of evt->type. Same for all other usages that do this.

2022-10-04 01:58 UTC, lsoldano93 commented on src/ControlScheme/StdKeyBoardCtrlScheme.cpp
> +		return shared_ptr<Command>(new NullCommand());
Remember to always use make_shared, so return std::make_shared<NullCommand>();

2022-10-04 01:58 UTC, lsoldano93 commented on src/ControlScheme/StdKeyBoardCtrlScheme.hpp
> +	~StdKeyControlScheme() = default;
Worth respecifying as virtual destructor, I always just get in the habit of being explicit about that to avoid annoying bugs later.

2022-10-04 01:58 UTC, lsoldano93 commented on src/ControlScheme/StdKeyBoardCtrlScheme.hpp
> +	std::map<SDL_Keycode, std::vector<std::shared_ptr<Command>>> m_scheme;
Similar comment about making this member variable name a little more clear onn intent

2022-10-05 02:12 UTC, csimpson1 commented on src/Command/Command.hpp
> +      ~Command() = default;
Fixed

2022-10-05 02:13 UTC, csimpson1 commented on src/ControlScheme/CMakeLists.txt
> +set(CONTROL_SCHEME_FILES
Fixed here and in the main makefile.

2022-10-05 02:16 UTC, csimpson1 commented on src/ControlScheme/CMakeLists.txt
>      #${CMAKE_CURRENT_LIST_DIR}/
Done for both comments

2022-10-05 02:18 UTC, csimpson1 commented on src/ControlScheme/ControlScheme.hpp
> +   /*
Correct. I can move this if need be, I just wanted it somewhere because I will forget what the convention is

2022-10-05 02:19 UTC, csimpson1 commented on src/ControlScheme/ControlScheme.hpp
> +      virtual std::shared_ptr<Command> translate(SDL_Event * e) = 0;
changed

2022-10-05 02:19 UTC, csimpson1 commented on src/ControlScheme/ControlScheme.hpp
> +      virtual std::shared_ptr<Command> translate(SDL_Event * e) = 0;
to translate_key_evt_to_command

2022-10-05 02:21 UTC, csimpson1 commented on src/ControlScheme/ControlScheme.hpp
> +      std::map<SDL_Keycode, std::vector<std::shared_ptr<Command>>> m_scheme;
changed to m_key_evt_to_command_map

2022-10-05 02:24 UTC, csimpson1 commented on src/ControlScheme/StdKeyBoardCtrlScheme.cpp
> +	this->m_scheme.emplace(SDLK_a, handleMoveLeft);
Sure. I see what you're saying. I've changed this to follow the first approach you suggested. How can I be aware of other situations like this going forward?

2022-10-05 02:33 UTC, csimpson1 commented on src/ControlScheme/StdKeyBoardCtrlScheme.cpp
> +			throw std::out_of_range("Command misspecified!");
That makes sense. For now I have changed this to log and return a null command.

2022-10-05 02:34 UTC, csimpson1 commented on src/ControlScheme/StdKeyBoardCtrlScheme.cpp
> -				else if(translatedEvent.length > 1 && *evt.type == SDL_KEYUP) {
changed

2022-10-05 02:34 UTC, csimpson1 commented on src/ControlScheme/StdKeyBoardCtrlScheme.cpp
> +		return shared_ptr<Command>(new NullCommand());
changed

2022-10-05 02:36 UTC, csimpson1 commented on src/ControlScheme/StdKeyBoardCtrlScheme.hpp
> +	~StdKeyControlScheme() = default;
done

2022-10-05 02:36 UTC, csimpson1 commented on src/ControlScheme/StdKeyBoardCtrlScheme.hpp
> +	std::map<SDL_Keycode, std::vector<std::shared_ptr<Command>>> m_scheme;
done

2022-10-05 02:52 UTC, csimpson1 commented on src/ControlScheme/StdKeyBoardCtrlScheme.cpp
> +	using std::vector;
I get checking for a null pointer here, but why should we return one from the translate function? For now have added in the CHECK_IF_POINTER_VALID macro

2022-10-05 03:36 UTC, lsoldano93 commented on src/ControlScheme/ControlScheme.hpp
> +   /*
Yeah I'd say comment above things just makes it clearer what it's for

2022-10-05 03:37 UTC, lsoldano93 commented on src/ControlScheme/ControlScheme.hpp
> +      std::map<SDL_Keycode, std::vector<std::shared_ptr<Command>>> m_scheme;
Dope, and thinking about this command map, what's the rationale for having a vector? Do we think there will ever more than two strokes possible (press & release)? Is it expected there will be more for something like mouse movements?

2022-10-05 03:51 UTC, lsoldano93 requested changes
Small changes needed, looks good otherwise

2022-10-05 03:51 UTC, lsoldano93 commented on src/ControlScheme/ControlScheme.hpp
> +      std::map<SDL_Keycode, std::vector<std::shared_ptr<Command>>> m_key_evt_to_command_map;
Ditto prior comment on what the motivation is for a vector of commands

2022-10-05 03:51 UTC, lsoldano93 commented on src/ControlScheme/StdKeyBoardCtrlScheme.cpp
>  #include <stdexcept>
For includes that we can remove, you dont need stdexcept anymore, and there's no need to reinclude map & vector as they were already included in your header when you defined the member type. All includes from the header transfer to source as well when you include that header. For that matter any one include includes everything included from its own inclusion headers, etc, etc. This is why it's good to minimize unnecessary includes, each one of these increase compile time if one of those headers is changed.

2022-10-05 03:51 UTC, lsoldano93 commented on src/ControlScheme/StdKeyBoardCtrlScheme.cpp
> +	using std::vector;
Are you asking why the function has to return a pointer in general? If so the answer is just simply because the function has to return some pointer if it fails. Arguably it could just return nullptr (as a sign of a failure) - not to be confused with NullCommand.

2022-10-05 03:51 UTC, lsoldano93 commented on src/ControlScheme/StdKeyBoardCtrlScheme.cpp
>  	catch (std::out_of_range) {
Need to get rid of the try catch block as it's no longer necessary

2022-10-05 03:51 UTC, lsoldano93 commented on src/ControlScheme/StdKeyBoardCtrlScheme.hpp
> +	std::map<SDL_Keycode, std::vector<std::shared_ptr<Command>>> m_key_evt_to_command_map;
Ditto question on why a vector

2022-10-05 03:51 UTC, lsoldano93 commented on src/ControlScheme/StdKeyBoardCtrlScheme.cpp
> +		vector<shared_ptr<Command>> translatedEvent = this->m_key_evt_to_command_map.at(key);
For what it's worth you don't need to specify this-> when accessing a class member, you can just say straight up m_key_event_to_command_map.at()... but I won't say it's bad to use it as a way to make it clear you're accessing a member, it's just mildly redundant given the 'm_' prefix. Your call!

2022-10-05 03:55 UTC, lsoldano93 commented on src/ControlScheme/StdKeyBoardCtrlScheme.cpp
> +	this->m_scheme.emplace(SDLK_a, handleMoveLeft);
It's tough to say that with a blanket statement, efficient memory management is often case by case, but I will say one thing to look for is if you ever create a variable that's only ever used once/you create a variable just to be stored in another variable's container type. Usually those would be when I'd look to see if I could initialize it during the second objects construction or if I don't want to, if I can just move the value into the second variable's container. 

Be warned after you move a variable, the initial variable is now in a bad state. So if you std::move(handleMoveLeft) DO NOT try to access that variable again after. Hence my comment above about for variables you "only use once". You blood sacrifice your variable for efficiency at the cost of murdering it. That being said moves aren't guaranteed to be more efficient, though they often do help.

2022-10-06 02:14 UTC, csimpson1 commented on src/ControlScheme/StdKeyBoardCtrlScheme.cpp
>  	catch (std::out_of_range) {
done

2022-10-06 02:15 UTC, csimpson1 commented on src/ControlScheme/StdKeyBoardCtrlScheme.cpp
>  	catch (std::out_of_range) {
Have also added a new macro which will return a nullptr should we take in a null ptr by mistake

2022-10-06 02:16 UTC, csimpson1 commented on src/ControlScheme/StdKeyBoardCtrlScheme.cpp
>  #include <stdexcept>
Thanks, have cleaned this up

2022-10-06 12:49 UTC, lsoldano93 approved these changes

2022-10-06 12:49 UTC, merged